version: "3"
services:
  api:
    build: .
    env_file: "secrets.yaml"
    depends_on:
      - postgres
    ports:
      - "80:8000"
    volumes:
      - ./:/usr/src/app:ro

  postgres:
    image: postgres:14.6
    user: postgres
    environment:
      - POSTGRES_PASSWORD=12345
#      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
